import { getAutoGeneratedLegends } from './get-auto-generated-legend-sets.helper';
import { generateUid, LegendSet } from 'src/app/core';

export function getAutoGeneratedLegendSet(legendSetName?: string): LegendSet {
  return {
    id: generateUid(),
    name: legendSetName || 'Default',
    legends: getAutoGeneratedLegends()
  };
}
